version: '2'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "db"
    depends_on:
      - "db"
    ports:
      - "8080:8080"